# Generated by Django 3.2.16 on 2022-11-18 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('isExhibitor', models.BooleanField(default=False, verbose_name='Exhibitor status')),
                ('isVisitor', models.BooleanField(default=False, verbose_name='Visitor status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('pinCode', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('website', models.URLField()),
                ('productAndServicecOffer', models.CharField(choices=[('0', ''), ('1', 'Exhibitions'), ('2', 'Conference'), ('3', 'Award Nights'), ('4', 'Weddings'), ('5', 'Birthday Parties'), ('6', 'Celebrations')], default='0', max_length=200)),
                ('briefProfile', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='VenderContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('Vender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vender')),
            ],
        ),
        migrations.CreateModel(
            name='Exhibitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=30)),
                ('contactPerson', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('department', models.CharField(choices=[('select', ''), ('Admin', 'Admin'), ('Business Development / Sales', 'Business Development / Sales'), ('Consultant', 'Consultant'), ('Distribution', 'Distribution')], default='select', max_length=30)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('boothNumber', models.CharField(max_length=30)),
                ('boothSize', models.IntegerField()),
                ('boothType', models.CharField(choices=[('0', ''), ('1', 'BARE SPACE'), ('2', 'SHELL SCHEME')], default='0', max_length=30)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
