# Generated by Django 3.2.16 on 2022-11-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='t_n_d',
            field=models.BooleanField(default=False),
        ),
    ]
