# Generated by Django 3.2.16 on 2022-11-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_t_n_d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='t_n_d',
            field=models.BooleanField(default=False, verbose_name='Terms & Conditions'),
        ),
    ]
