# Generated by Django 3.2.16 on 2022-11-30 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0001_initial'),
        ('core', '0004_auto_20221123_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitor',
            name='senior_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='senior_department', to='utility.department'),
        ),
    ]
