# Generated by Django 3.2.16 on 2022-12-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_exhibitor_senior_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitor',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
