# Generated by Django 3.2.16 on 2022-12-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_exhibitor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
