# Generated by Django 3.2.16 on 2022-12-08 06:01

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0003_howdidyougettoknowaboutintimasia_nationality_organization'),
        ('core', '0007_auto_20221206_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=49)),
                ('last_name', models.CharField(max_length=49)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=49)),
                ('job_title', models.CharField(max_length=49)),
                ('apartment_unit_building_floor_etc', models.TextField()),
                ('street_address', models.TextField()),
                ('zip_code', models.CharField(max_length=49)),
                ('country', models.CharField(max_length=49)),
                ('state', models.CharField(max_length=49)),
                ('town_city_district', models.CharField(max_length=49)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cc_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('whatsapp', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('nature_of_business_others', models.TextField(blank=True, null=True)),
                ('product_category_others', models.TextField(blank=True, null=True)),
                ('product_sub_category_others', models.TextField(blank=True, null=True)),
                ('brand_others', models.TextField(blank=True, null=True)),
                ('product_category_interest_others', models.TextField(blank=True, null=True)),
                ('product_sub_category_interest_others', models.TextField(blank=True, null=True)),
                ('subscribe_to_inner_secrets', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=128)),
                ('is_first_time_to_intimasia', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=128)),
                ('brand', models.ManyToManyField(to='utility.Brand')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utility.department')),
                ('how_did_you_get_to_know_about_INTIMASIA', models.ManyToManyField(to='utility.HowDidYouGetToKnowAboutINTIMASIA')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utility.nationality')),
                ('nature_of_business', models.ManyToManyField(to='utility.NatureOfBusiness')),
                ('organization_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utility.organization')),
                ('product_category', models.ManyToManyField(related_name='product_category', to='utility.ProductCatogory')),
                ('product_category_interest', models.ManyToManyField(related_name='product_category_interest', to='utility.ProductCatogory')),
                ('product_sub_category', models.ManyToManyField(related_name='product_sub_category', to='utility.ProductSubCatogory')),
                ('product_sub_category_interest', models.ManyToManyField(related_name='product_sub_category_interest', to='utility.ProductSubCatogory')),
            ],
        ),
    ]
