# Generated by Django 3.2.16 on 2022-12-12 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_visitor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
