# Generated by Django 3.2.16 on 2022-12-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_id',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
