# Generated by Django 3.2.16 on 2022-12-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_visitor_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='gender',
            field=models.CharField(choices=[('', '-----'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=49),
        ),
    ]
