# Generated by Django 3.2.16 on 2022-12-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_visitor_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='how_did_you_get_to_know_about_INTIMASIA_others',
            field=models.TextField(blank=True, null=True),
        ),
    ]
