# Generated by Django 3.2.16 on 2022-12-12 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_visitor_how_did_you_get_to_know_about_intimasia_others'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.visitor'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='type',
            field=models.CharField(choices=[('', '---'), ('VIP', 'VIP'), ('NON-VIP', 'NON-VIP')], default='NON-VIP', max_length=255),
        ),
    ]
