# Generated by Django 3.2.16 on 2022-12-12 12:12

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0003_howdidyougettoknowaboutintimasia_nationality_organization'),
        ('core', '0017_auto_20221212_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='apartment_unit_building_floor_etc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='brand',
            field=models.ManyToManyField(blank=True, null=True, to='utility.Brand'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='utility.department'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='gender',
            field=models.CharField(blank=True, choices=[('', '-----'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='how_did_you_get_to_know_about_INTIMASIA',
            field=models.ManyToManyField(blank=True, null=True, to='utility.HowDidYouGetToKnowAboutINTIMASIA'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='is_first_time_to_intimasia',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='utility.nationality'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='nature_of_business',
            field=models.ManyToManyField(blank=True, null=True, to='utility.NatureOfBusiness'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='organization_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='utility.organization'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='product_category',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_category', to='utility.ProductCatogory'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='product_category_interest',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_category_interest', to='utility.ProductCatogory'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='product_sub_category',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_sub_category', to='utility.ProductSubCatogory'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='product_sub_category_interest',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_sub_category_interest', to='utility.ProductSubCatogory'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='street_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='subscribe_to_inner_secrets',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='town_city_district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='zip_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
