# Generated by Django 3.2.16 on 2022-12-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20221212_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='cc_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
