# Generated by Django 3.2.16 on 2022-12-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_visitor_organization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='dont_use_whatsapp',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='whatsapp_same_as_mobile',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
