# Generated by Django 3.2.16 on 2022-12-14 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20221214_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='dont_use_whatsapp',
            new_name='whatsapp_same_as_mobile_or_no_wp',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='whatsapp_same_as_mobile',
        ),
    ]
