# Generated by Django 3.2.16 on 2022-12-15 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_visitoridpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitoridpassword',
            name='visitor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
