# Generated by Django 3.2.16 on 2022-12-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_visitor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
