# Generated by Django 3.2.16 on 2022-12-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0004_auto_20221221_1547'),
        ('core', '0029_visitor_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitoridpassword',
            options={'verbose_name': 'visitoridpassword', 'verbose_name_plural': 'Visitor ID and Password'},
        ),
        migrations.AlterField(
            model_name='exhibitor',
            name='nature_of_bussiness',
            field=models.ManyToManyField(blank=True, related_name='nature_of_bussiness', to='utility.NatureOfBusiness'),
        ),
    ]
