# Generated by Django 3.2.16 on 2022-12-22 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0004_auto_20221221_1547'),
        ('core', '0030_auto_20221221_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitor',
            name='our_brand',
            field=models.ManyToManyField(blank=True, related_name='brand', to='utility.Brand'),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.SmallIntegerField(choices=[('1', 'VISITOR'), ('2', 'EXHIBITOR')])),
                ('schedule_time', models.TimeField(verbose_name='Schedule Time')),
                ('status', models.BooleanField(blank=True, null=True)),
                ('schedule_request_time', models.TimeField()),
                ('exhibitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.exhibitor')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.visitor')),
            ],
        ),
    ]
