# Generated by Django 3.2.16 on 2022-12-23 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0004_auto_20221221_1547'),
        ('core', '0031_auto_20221222_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='personal_message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exhibitor',
            name='nature_of_bussiness',
            field=models.ManyToManyField(blank=True, to='utility.NatureOfBusiness'),
        ),
        migrations.AlterField(
            model_name='exhibitor',
            name='our_brand',
            field=models.ManyToManyField(blank=True, to='utility.Brand'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='schedule_request_time',
            field=models.TimeField(auto_now=True, verbose_name='Schedule Request Time'),
        ),
        migrations.CreateModel(
            name='MySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('exhibitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.exhibitor')),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.visitor')),
            ],
        ),
    ]
