# Generated by Django 3.2.16 on 2022-12-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20221227_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='schedule_request_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Schedule Request Time'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='schedule_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Schedule Time'),
        ),
        migrations.AlterField(
            model_name='myschedule',
            name='time_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='myschedule',
            name='time_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
