# Generated by Django 3.2.16 on 2022-12-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0004_auto_20221221_1547'),
        ('core', '0035_exhibitor_company_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='brand',
            field=models.ManyToManyField(blank=True, to='utility.Brand'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='how_did_you_get_to_know_about_INTIMASIA',
            field=models.ManyToManyField(blank=True, to='utility.HowDidYouGetToKnowAboutINTIMASIA'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='nature_of_business',
            field=models.ManyToManyField(blank=True, to='utility.NatureOfBusiness'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='product_category',
            field=models.ManyToManyField(blank=True, related_name='product_category', to='utility.ProductCatogory'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='product_category_interest',
            field=models.ManyToManyField(blank=True, related_name='product_category_interest', to='utility.ProductCatogory'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='product_sub_category',
            field=models.ManyToManyField(blank=True, related_name='product_sub_category', to='utility.ProductSubCatogory'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='product_sub_category_interest',
            field=models.ManyToManyField(blank=True, related_name='product_sub_category_interest', to='utility.ProductSubCatogory'),
        ),
    ]
