# Generated by Django 3.2.16 on 2023-01-02 02:40

import core.models
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20221228_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='company_telphone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='fascia_name',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='interested_in_oem_or_private_label_mfg',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='sd_key_person_designation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='sd_key_person_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='sd_key_person_first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='sd_key_person_last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='sd_key_person_mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='upload_company_or_brand_logo',
            field=models.FileField(blank=True, null=True, upload_to='images/exhibitor/downloads/company-brand-logo/', validators=[core.models.company_or_brand_logo, core.models.file_size]),
        ),
    ]
