# Generated by Django 3.2.16 on 2023-01-02 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0004_auto_20221221_1547'),
        ('core', '0038_auto_20230102_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='sd_key_person_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sd_key_person_department', to='utility.department'),
        ),
    ]
