# Generated by Django 3.2.16 on 2023-01-04 09:03

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20230104_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitorBrandOrCompanyLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='images/exhibitor/downloads/company-brand-logo/', validators=[core.models.company_or_brand_logo, core.models.file_size])),
                ('Exhibitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exhibitor')),
            ],
        ),
    ]
