# Generated by Django 3.2.16 on 2023-01-08 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_meeting_sender_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myschedule',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='myschedule',
            name='date',
        ),
        migrations.RemoveField(
            model_name='myschedule',
            name='exhibitor',
        ),
        migrations.RemoveField(
            model_name='myschedule',
            name='message',
        ),
        migrations.RemoveField(
            model_name='myschedule',
            name='sender_to_receiver_type',
        ),
        migrations.RemoveField(
            model_name='myschedule',
            name='time_from',
        ),
        migrations.RemoveField(
            model_name='myschedule',
            name='time_to',
        ),
        migrations.RemoveField(
            model_name='myschedule',
            name='visitor',
        ),
        migrations.AddField(
            model_name='myschedule',
            name='meetings',
            field=models.ManyToManyField(blank=True, to='core.Meeting'),
        ),
        migrations.AddField(
            model_name='myschedule',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='sender_type',
            field=models.CharField(choices=[('0', '---'), ('VISITOR', 'VISITOR'), ('EXHIBITOR', 'EXHIBITOR')], max_length=255),
        ),
    ]
