# Generated by Django 3.2.16 on 2023-01-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20230109_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventagenda',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventagenda',
            name='speaker',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventagenda',
            name='topic',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
