# Generated by Django 3.2.16 on 2023-01-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20230110_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventagenda',
            name='speaker',
            field=models.TextField(blank=True, null=True),
        ),
    ]
