# Generated by Django 3.2.16 on 2022-12-08 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_visitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitorDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='images/exhibitor/downloads')),
                ('exhibitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exhibitor')),
            ],
        ),
    ]
