# Generated by Django 3.2.16 on 2022-12-15 12:35

import Exhibitor_utility.models
import Exhibitor_utility.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exhibitor_utility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to=Exhibitor_utility.models.generate_pdf_file_name, validators=[Exhibitor_utility.validators.pdf_file_extension])),
                ('jpg_file', models.FileField(upload_to=Exhibitor_utility.models.generate_jpg_file_name_for_StaticDownload, validators=[Exhibitor_utility.validators.jpg_file_extension])),
                ('ai_file', models.FileField(upload_to=Exhibitor_utility.models.generate_ai_file_name, validators=[Exhibitor_utility.validators.ai_file_extension])),
                ('thumbnail_file', models.FileField(upload_to=Exhibitor_utility.models.generate_thumbnail_file_name, validators=[Exhibitor_utility.validators.jpg_file_extension])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='exhibitordownload',
            name='file',
            field=models.FileField(upload_to=Exhibitor_utility.models.generate_jpg_file_name_for_ExhibitorDownload, validators=[Exhibitor_utility.validators.jpg_file_extension]),
        ),
    ]
