# Generated by Django 3.2.16 on 2022-12-21 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exhibitor_utility', '0002_auto_20221215_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staticdownload',
            options={'verbose_name': 'Event Creative', 'verbose_name_plural': 'Event Creatives'},
        ),
    ]
