# Generated by Django 3.2.16 on 2022-12-23 10:21

import Exhibitor_utility.models
import Exhibitor_utility.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20221222_1831'),
        ('Exhibitor_utility', '0003_alter_staticdownload_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to=Exhibitor_utility.models.generate_pdf_file_name_for_FloorPlans, validators=[Exhibitor_utility.validators.pdf_file_extension])),
                ('thumbnail_file', models.FileField(upload_to=Exhibitor_utility.models.generate_thumbnail_file_name_for_FloorPlans, validators=[Exhibitor_utility.validators.jpg_file_extension])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Floor Plan',
                'verbose_name_plural': 'Floor Plans',
            },
        ),
        migrations.CreateModel(
            name='PromotionalCreative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('thumbnail_file', models.FileField(upload_to=Exhibitor_utility.models.generate_thumbnail_file_name_for_PromotionalCreatives, validators=[Exhibitor_utility.validators.jpg_file_extension])),
                ('jpg_file', models.FileField(upload_to=Exhibitor_utility.models.generate_jpg_file_name_for_PromotionalCreatives, validators=[Exhibitor_utility.validators.jpg_file_extension])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exhibitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.exhibitor')),
            ],
            options={
                'verbose_name': 'Promotional Creative',
                'verbose_name_plural': 'Promotional Creatives',
            },
        ),
    ]
