# Generated by Django 3.2.16 on 2022-12-27 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exhibitor_utility', '0004_floorplan_promotionalcreative'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibitordownload',
            options={'verbose_name': 'Email Signature', 'verbose_name_plural': 'Email Signatures'},
        ),
    ]
