# Generated by Django 3.2.16 on 2022-12-07 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Designation',
        ),
    ]
